version: '3.7'

services:
    node1:
        image: mariadb:10.11
        hostname: node1
        ports:
          - 13306:3306
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-test}
          - MYSQL_DATABASE=maria
          - MYSQL_USER=maria
          - MYSQL_PASSWORD=${MYSQL_PASSWORD:-test}
          - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-test}
        volumes:
          - node1_data:/var/lib/mysql
        command:
          - --wsrep-new-cluster
          - --wsrep-node-name=node1
          - --wsrep-cluster-name=maria_cluster
          - --wsrep-cluster-address=gcomm://
          - --wsrep-sst-method=rsync
        healthcheck:
          test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
          interval: 10s
          timeout: 5s
          retries: 5

    node2:
        image: mariadb:10.11
        hostname: node2
        ports:
          - 23306:3306
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-test}
          - MYSQL_DATABASE=maria
          - MYSQL_USER=maria
          - MYSQL_PASSWORD=${MYSQL_PASSWORD:-test}
          - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-test}
        volumes:
          - node2_data:/var/lib/mysql
        links:
          - node1
        depends_on:
          - node1
        command:
          - --wsrep-node-name=node2
          - --wsrep-cluster-name=maria_cluster
          - --wsrep-cluster-address=gcomm://node1
          - --wsrep-sst-method=rsync
        healthcheck:
          test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
          interval: 10s
          timeout: 5s
          retries: 5

    node3:
        image: mariadb:10.11
        hostname: node3
        ports:
          - 33306:3306
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-test}
          - MYSQL_DATABASE=maria
          - MYSQL_USER=maria
          - MYSQL_PASSWORD=${MYSQL_PASSWORD:-test}
          - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD:-test}
        volumes:
          - node3_data:/var/lib/mysql
        links:
          - node1
        depends_on:
          - node1
        command:
          - --wsrep-node-name=node3
          - --wsrep-cluster-name=maria_cluster
          - --wsrep-cluster-address=gcomm://node1
          - --wsrep-sst-method=rsync
        healthcheck:
          test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
          interval: 10s
          timeout: 5s
          retries: 5

volumes:
    node1_data:
    node2_data:
    node3_data:
